import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs:
    [
      {
        type: 'autogenerated',
        dirName: 'docs',
      },
    ],
  enDocs: [
    {
      type: 'autogenerated',
      dirName: 'en',
    },
    {
      type: 'link',
      href: '/docs/learning_resources',
      label: '返回中文文档 ↗️',
    },
  ],
};

export default sidebars;